export const FAKE_POPULARS = [
  {
    backdrop_path: "/t2rAdgjSh0WYbXzdOB5zTDqzdCI.jpg",
    first_air_date: "2022-11-02",
    genre_ids: [18],
    id: 213713,
    name: "Faltu",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Faltu",
    overview:
      "What's in a name? Amidst the arid landscape of Rajasthan, a young woman with dreamy eyes struggles to prove her worth.",
    popularity: 2879.422,
    poster_path: "/lgyFuoXs7GvKJN0mNm7z7OMOFuZ.jpg",
    vote_average: 7,
    vote_count: 53,
  },
  {
    backdrop_path: "/3n2TjKw3HrwDqgVgcynvantOfS3.jpg",
    first_air_date: "2023-01-04",
    genre_ids: [18, 10751],
    id: 215103,
    name: "Teri Meri Doriyaann",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "तेरी मेरी डोरियाँ",
    overview:
      "It’s hate at first sight for Sahiba and Angad! But destined to be together, their lives get intertwined by a marriage alliance, and a love-hate story ensues.",
    popularity: 2740.892,
    poster_path: "/4BHDmYiuSnNL3nqKIOzLJKYX4AN.jpg",
    vote_average: 6.4,
    vote_count: 41,
  },
  {
    backdrop_path: null,
    first_air_date: "2022-11-28",
    genre_ids: [18],
    id: 215315,
    name: "Rabb Se Hai Dua",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "रब्ब से है दुआ",
    overview:
      "Dua and her husband are a perfect married couple in the eyes of their family. However, Dua’s life turns upside down when her husband seeks her permission to marry another woman.",
    popularity: 2724.647,
    poster_path: "/6ikbefd7VeopbBuGgioYMNU5bQj.jpg",
    vote_average: 5.9,
    vote_count: 22,
  },
  {
    backdrop_path: "/i8NGdMIyZnGNpSHLDtpPwYXidPe.jpg",
    first_air_date: "2020-11-16",
    genre_ids: [18, 10766, 10751],
    id: 113218,
    name: "Imlie",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "इमली",
    overview:
      "All Imlie wanted was to create a name for herself in the city. But upon her arrival, she finds herself caught in the middle of Aditya and Malini's love story.",
    popularity: 2188.84,
    poster_path: "/sltUDXvpDZK3aVIdtkbImhcJv8t.jpg",
    vote_average: 7,
    vote_count: 31,
  },
  {
    backdrop_path: "/viVwEfLEGBsgq5CId68jqXKooAx.jpg",
    first_air_date: "2021-08-08",
    genre_ids: [10764],
    id: 130780,
    name: "Bigg Boss OTT",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Bigg Boss OTT",
    overview:
      "Sass aur Sazish, Drama aur Romance... itna over the top ke TV pe ban ho jayega! Karan Johar flags off the first-ever, the digital-only season of Bigg Boss with the bigg promise of gossip, controversies & uncensored drama. And let's just say... he's going to take it ALL #OverTheTop!",
    popularity: 1212.364,
    poster_path: "/sYrQoN38sJ2LqMN698Nwljh4Hbe.jpg",
    vote_average: 6.9,
    vote_count: 11,
  },
  {
    backdrop_path: "/kdF7ZTktLHVVhAhI90uuzqlZqJI.jpg",
    first_air_date: "2023-06-06",
    genre_ids: [18],
    id: 228093,
    name: "Titlie",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Titlie",
    overview:
      "Obsessed by the notion of fairy tale love , Titlie marries her beau Garv . Soon , the picture - perfect romance turns abusive , forcing her to wrestle with reality .",
    popularity: 1996.23,
    poster_path: "/5kZi1LCFugNAeDCWOF3ornGNm2W.jpg",
    vote_average: 7.8,
    vote_count: 26,
  },
  {
    backdrop_path: "/5e1MxLWTJh6n4qtYz0vlevOK6qW.jpg",
    first_air_date: "2023-07-03",
    genre_ids: [18],
    id: 229932,
    name: "Pyaar Ka Pehla Adhyaya  - Shiv Shakti",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Pyaar Ka Pehla Adhyaya  - Shiv Shakti",
    overview:
      "Shiv has a rewarding career as a doctor, but his personal life is in tatters. Shakti, an orphan, is a nurturer by nature. Will Shakti heal a broken Shiv?",
    popularity: 1902.609,
    poster_path: "/jHK9bCDefHq43cHvMVUM7SLumYF.jpg",
    vote_average: 8,
    vote_count: 5,
  },
  {
    backdrop_path: "/wq269s8vzr8xrwrIALtl4UfmN6X.jpg",
    first_air_date: "2023-06-12",
    genre_ids: [],
    id: 228627,
    name: "Do Dil Mil Rahe Hai",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Do Dil Mil Rahe Hai",
    overview:
      "He repels love , she resembles it ! Rishi and Pihu are worlds apart but unaware of the past that connects them . Will fate lead the duo down the road to true love ?",
    popularity: 1944.867,
    poster_path: "/juYg1PQzCmDJYyGtrW0Xbvke1jx.jpg",
    vote_average: 7.9,
    vote_count: 14,
  },
  {
    backdrop_path: "/7RXAXlmPqCY88xRjNQ88vhAF9GU.jpg",
    first_air_date: "2023-07-12",
    genre_ids: [18],
    id: 134679,
    name: "The Legend of Anle",
    origin_country: ["CN"],
    original_language: "zh",
    original_name: "安乐传",
    overview:
      "Legend has it that the Han and Di families together established the Great Jing. However, ten years ago, the Di family was convicted of treason, leaving behind only one orphaned girl imprisoned in Daishan. Ten years later, Han Ye, the determined crown prince who aimed to rescue the Di family's lone survivor, unexpectedly crossed paths with a spirited and enchanting female pirate who claimed that she would marry none other than him. She called herself Ren Anle and brought with her a fleet of thirty thousand soldiers, arriving in the capital city to seek the prince's hand in marriage. Throughout the process of relentlessly pursuing Han Ye, Ren Anle demonstrated remarkable wit and intelligence. As their shared values and national aspirations aligned, Han Ye couldn't help but develop affection for Ren Anle.",
    popularity: 1919.833,
    poster_path: "/td2imRpNMZBbl3kXU2laYAFdqDL.jpg",
    vote_average: 8.2,
    vote_count: 10,
  },
  {
    backdrop_path: "/xYTSIhkbvj6eVN8GxozdEXi6piA.jpg",
    first_air_date: "2023-06-04",
    genre_ids: [],
    id: 226658,
    name: "La Casa de los Famosos Mexico",
    origin_country: ["MX"],
    original_language: "es",
    original_name: "La Casa de los Famosos Mexico",
    overview: "La Casa de los Famosos Mexico",
    popularity: 2019.5,
    poster_path: "/uh2NbTkUheENmBlUs7Kwb5EaAXQ.jpg",
    vote_average: 7.9,
    vote_count: 35,
  },
  {
    backdrop_path: "/57clBMPX25NNO6nmDw3TV3zQaQE.jpg",
    first_air_date: "2023-06-21",
    genre_ids: [18, 10765, 10759],
    id: 114472,
    name: "Secret Invasion",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Secret Invasion",
    overview:
      "Nick Fury and Talos discover a faction of shapeshifting Skrulls who have been infiltrating Earth for years.",
    popularity: 1465.573,
    poster_path: "/f5ZMzzCvt2IzVDxr54gHPv9jlC9.jpg",
    vote_average: 7.4,
    vote_count: 510,
  },
  {
    backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    first_air_date: "2021-08-03",
    genre_ids: [10766],
    id: 130542,
    name: "Bhagya Lakshmi",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "Bhagya Lakshmi",
    overview:
      "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
    popularity: 1363.179,
    poster_path: "/eVaGfVPA85AUrCAQoOLb0kY2SZA.jpg",
    vote_average: 5.6,
    vote_count: 64,
  },
  {
    backdrop_path: "/d1ujVe5yWPJ6mtepghxidUYIJa5.jpg",
    first_air_date: "2020-10-05",
    genre_ids: [18, 10766, 10751],
    id: 111453,
    name: "Ghum Hai Kisikey Pyaar Meiin",
    origin_country: ["IN"],
    original_language: "hi",
    original_name: "घुम है किसिकी प्यार में",
    overview:
      "Virat sacrifices his love to honour the promise he made to a dying man. Trapped between the past and the present, will he find love beyond the chains of duty?",
    popularity: 1310.205,
    poster_path: "/u3NVGYCpkAgBArXogLuHPfpSNwG.jpg",
    vote_average: 5.6,
    vote_count: 56,
  },
  {
    backdrop_path: "/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg",
    first_air_date: "2023-05-08",
    genre_ids: [18, 80, 10766],
    id: 209265,
    name: "Terra e Paixão",
    origin_country: ["BR"],
    original_language: "pt",
    original_name: "Terra e Paixão",
    overview: "",
    popularity: 1781.872,
    poster_path: "/5kCMJ0vVzN9PsoamKctNnUz68Q2.jpg",
    vote_average: 6,
    vote_count: 71,
  },
  {
    backdrop_path: "/mAJ84W6I8I272Da87qplS2Dp9ST.jpg",
    first_air_date: "2023-01-23",
    genre_ids: [9648, 18],
    id: 202250,
    name: "Dirty Linen",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Dirty Linen",
    overview:
      "To exact vengeance, a young woman infiltrates the household of an influential family as a housemaid to expose their dirty secrets. However, love will get in the way of her revenge plot.",
    popularity: 1103.427,
    poster_path: "/aoAZgnmMzY9vVy9VWnO3U5PZENh.jpg",
    vote_average: 6.7,
    vote_count: 63,
  },
  {
    backdrop_path: "/foGkPxpw9h8zln81j63mix5B7m8.jpg",
    first_air_date: "2019-12-20",
    genre_ids: [18, 10759, 10765],
    id: 71912,
    name: "The Witcher",
    origin_country: ["US"],
    original_language: "en",
    original_name: "The Witcher",
    overview:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    popularity: 1085.763,
    poster_path: "/cZ0d3rtvXPVvuiX22sP79K3Hmjz.jpg",
    vote_average: 8.2,
    vote_count: 4961,
  },
  {
    backdrop_path: "/odDW9tvqrHenN4TWizdV6iggLHo.jpg",
    first_air_date: "2019-07-09",
    genre_ids: [10764],
    id: 90521,
    name: "Love Island",
    origin_country: ["US"],
    original_language: "en",
    original_name: "Love Island",
    overview:
      "American version of the British dating reality competition in which ten singles come to stay in a villa for a few weeks and have to couple up with one another. Over the course of those weeks, they face the public vote and might be eliminated from the show. Other islanders join and try to break up the couples.",
    popularity: 1432.764,
    poster_path: "/kU2y21cls8WargMaX7KI47URMjD.jpg",
    vote_average: 7.2,
    vote_count: 66,
  },
  {
    backdrop_path: "/1Xm0WqoT0DjZm5JdG2V6YFabrOz.jpg",
    first_air_date: "2023-02-13",
    genre_ids: [10759, 35, 18],
    id: 215803,
    name: "Batang Quiapo",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Batang Quiapo",
    overview:
      "A young man rises to be one of the biggest outlaws in the neighborhood while he navigates his way in life to survive in Quiapo. Hoping to earn the affection of his parents, his feat draws him closer to the truth about his identity.",
    popularity: 1379.062,
    poster_path: "/9McqS8mgMf5NJCAKZIY6J1oOl8y.jpg",
    vote_average: 7.4,
    vote_count: 62,
  },
  {
    backdrop_path: "/znjIKAlfJTkcWw6pcD6Bxm4L3dq.jpg",
    first_air_date: "2023-01-16",
    genre_ids: [18],
    id: 215546,
    name: "Luv Is",
    origin_country: ["PH"],
    original_language: "tl",
    original_name: "Luv Is",
    overview:
      "A Philippine seasonal anthology TV adaptations of the popular Filipino Wattpad web novels. Produced by GMA Network in partnership with Wattpad Webtoon Studios.",
    popularity: 1362.502,
    poster_path: "/nwKL1HEx6IwK2cMzXFM9c0V1F3y.jpg",
    vote_average: 7.7,
    vote_count: 18,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
    id: 1396,
    name: "Breaking Bad",
    original_language: "en",
    original_name: "Breaking Bad",
    overview:
      "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    media_type: "tv",
    genre_ids: [18, 80],
    popularity: 259.927,
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 12073,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/uGy4DCmM33I7l86W7iCskNkvmLD.jpg",
    id: 60625,
    name: "Rick and Morty",
    original_language: "en",
    original_name: "Rick and Morty",
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: "/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg",
    media_type: "tv",
    genre_ids: [16, 35, 10765, 10759],
    popularity: 220.641,
    first_air_date: "2013-12-02",
    vote_average: 8.71,
    vote_count: 8429,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/aWPhMZ0P2DyfWB7k5NXhGHSZHGC.jpg",
    id: 209265,
    name: "Land of Desire",
    original_language: "pt",
    original_name: "Terra e Paixão",
    overview:
      "The saga of a woman, guided by the power of love and moved by the desire for justice, who crosses paths with a family divided by ambition and many secrets.",
    poster_path: "/5kCMJ0vVzN9PsoamKctNnUz68Q2.jpg",
    media_type: "tv",
    genre_ids: [18, 80, 10766],
    popularity: 1805.637,
    first_air_date: "2023-05-08",
    vote_average: 5.9,
    vote_count: 80,
    origin_country: ["BR"],
  },
  {
    adult: false,
    backdrop_path: "/3Yg9TURGv1WUlFIGOhDMLM6mOHY.jpg",
    id: 218886,
    name: "Al Aghar",
    original_language: "ar",
    original_name: "الأجهر",
    overview:
      "Falsely accused of killing his mom, a teen continues his life abroad on the run. But his return home to find his family uncovers mysterious secrets about his past.",
    poster_path: "/sXxCcEKSkloJizPlCGsIBXVGCMC.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 7.402,
    first_air_date: "2023-03-23",
    vote_average: 6.5,
    vote_count: 4,
    origin_country: ["EG"],
  },
  {
    adult: false,
    backdrop_path: "/rkB4LyZHo1NHXFEDHl9vSD9r1lI.jpg",
    id: 94605,
    name: "Arcane",
    original_language: "en",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.",
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    media_type: "tv",
    genre_ids: [16, 18, 10765, 10759],
    popularity: 53.315,
    first_air_date: "2021-11-06",
    vote_average: 8.75,
    vote_count: 3203,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/hPea3Qy5Gd6z4kJLUruBbwAH8Rm.jpg",
    id: 60059,
    name: "Better Call Saul",
    original_language: "en",
    original_name: "Better Call Saul",
    overview:
      'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
    poster_path: "/fC2HDm5t0kHl7mTm7jxMR31b7by.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 116.518,
    first_air_date: "2015-02-08",
    vote_average: 8.633,
    vote_count: 4216,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/ds1n5P0Y92cTh6UpbcA89hxM96a.jpg",
    id: 1416,
    name: "Grey's Anatomy",
    original_language: "en",
    original_name: "Grey's Anatomy",
    overview:
      "Follows the personal and professional lives of a group of doctors at Seattle’s Grey Sloan Memorial Hospital.",
    poster_path: "/daSFbrt8QCXV2hSwB0hqYjbj681.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 753.382,
    first_air_date: "2005-03-27",
    vote_average: 8.254,
    vote_count: 9362,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/3FLHePl9Y3n4BidLVjIA9qSRDOE.jpg",
    id: 130542,
    name: "Bhagya Lakshmi",
    original_language: "hi",
    original_name: "Bhagya Lakshmi",
    overview:
      "Hailing from a middle-class family, Lakshmi’s life is upended when she realises that her marriage to Rishi Oberoi, an industrialist’s son, is a sham to keep his death at bay.",
    poster_path: "/eVaGfVPA85AUrCAQoOLb0kY2SZA.jpg",
    media_type: "tv",
    genre_ids: [10766],
    popularity: 1369.341,
    first_air_date: "2021-08-03",
    vote_average: 5.188,
    vote_count: 72,
    origin_country: ["IN"],
  },
  {
    adult: false,
    backdrop_path: "/azWBrlovNOOdy0eQYEe9BoiROoN.jpg",
    id: 209085,
    name: "Perfect Love",
    original_language: "pt",
    original_name: "Amor Perfeito",
    overview:
      "A story about love and its different manifestations, told through the little boy Marcelino in search of his biggest dream: to meet his mother. Inspired by a famous book, the plot takes place in the 1940s.",
    poster_path: "/g0Tb0bs0MBZoq37BpyFExcepbFX.jpg",
    media_type: "tv",
    genre_ids: [18, 10766],
    popularity: 9.034,
    first_air_date: "2023-03-20",
    vote_average: 6.1,
    vote_count: 38,
    origin_country: ["BR"],
  },
  {
    adult: false,
    backdrop_path: "/zEj8eKk2Z3OG8zo9IjpHXSjKA3Y.jpg",
    id: 203763,
    name: "Udan Patolas",
    original_language: "hi",
    original_name: "Udan Patolas",
    overview:
      "4 small town girls try to hilariously fit in the big city. They maybe unlucky in love but their sisterhood is unbreakable.",
    poster_path: "/pB090Pg2RKr6g59FNEIp6zc7mZ7.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 1.896,
    first_air_date: "2022-06-10",
    vote_average: 9,
    vote_count: 3,
    origin_country: ["IN"],
  },
];
